CREATE TABLE IF NOT EXISTS stalls_status (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  stall_name TEXT UNIQUE NOT NULL,
  crowd_level INTEGER DEFAULT 0,
  stock_level INTEGER DEFAULT 0,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

CREATE TABLE IF NOT EXISTS news (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  content TEXT NOT NULL,
  edit_reason TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

CREATE TABLE IF NOT EXISTS lost_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  place TEXT NOT NULL,
  edit_reason TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

CREATE TABLE IF NOT EXISTS questions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  text TEXT NOT NULL,
  answer TEXT,
  edit_reason TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

CREATE INDEX IF NOT EXISTS idx_news_created_at ON news (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_lost_items_created_at ON lost_items (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_questions_created_at ON questions (created_at DESC);

ALTER TABLE stalls_status ENABLE ROW LEVEL SECURITY;
ALTER TABLE news ENABLE ROW LEVEL SECURITY;
ALTER TABLE lost_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE questions ENABLE ROW LEVEL SECURITY;

DO $$
DECLARE
  r RECORD;
BEGIN
  FOR r IN SELECT tablename FROM pg_tables WHERE schemaname = 'public'
  LOOP
    EXECUTE 'DROP POLICY IF EXISTS "Public Read" ON ' || quote_ident(r.tablename);
    EXECUTE 'DROP POLICY IF EXISTS "Admin Full Access" ON ' || quote_ident(r.tablename);
  END LOOP;

  DROP POLICY IF EXISTS "Allow Public Insert" ON questions;
  DROP POLICY IF EXISTS "Allow Public Insert" ON lost_items;
END $$;

CREATE POLICY "Public Read" ON stalls_status FOR SELECT USING (true);
CREATE POLICY "Public Read" ON news FOR SELECT USING (true);
CREATE POLICY "Public Read" ON lost_items FOR SELECT USING (true);
CREATE POLICY "Public Read" ON questions FOR SELECT USING (true);

CREATE POLICY "Allow Public Insert" ON questions FOR INSERT WITH CHECK (true);

CREATE POLICY "Admin Full Access" ON stalls_status FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Admin Full Access" ON news FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Admin Full Access" ON lost_items FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Admin Full Access" ON questions FOR ALL TO authenticated USING (true) WITH CHECK (true);

CREATE OR REPLACE FUNCTION get_all_data()
RETURNS JSON AS $$
DECLARE
  result JSON;
BEGIN
  SELECT json_build_object(
    'stalls', (SELECT json_agg(s) FROM (SELECT * FROM stalls_status ORDER BY stall_name ASC) s),
    'news', (SELECT json_agg(n) FROM (SELECT * FROM news ORDER BY created_at DESC) n),
    'lost_items', (SELECT json_agg(l) FROM (SELECT * FROM lost_items ORDER BY created_at DESC) l),
    'questions', (SELECT json_agg(q) FROM (SELECT * FROM questions ORDER BY created_at DESC) q)
  ) INTO result;

  RETURN result;
END;
$$ LANGUAGE plpgsql;

INSERT INTO stalls_status (stall_name) VALUES
('たこ焼き'), ('焼きそば'), ('チョコバナナ'), ('チュロス'),
('わたあめ'), ('フランクフルト'), ('ポテト'), ('唐揚げ')
ON CONFLICT (stall_name) DO NOTHING;